let numberone = 18;
let numbertwo = 20; 
let sum = numberone + numbertwo;
let subtract = numbertwo - numberone ;
let mul = numberone * numbertwo;
let div = numbertwo / numberone;
console.log("The sum of "+numberone+" And "+numbertwo+" is :"+sum);
console.log("The Minus of "+numberone+" And "+numbertwo+" is :"+subtract);
console.log("the product of "+numberone+" and "+numbertwo+" is :"+mul);
console.log("The divison of "+numberone+" And "+numbertwo+" is :"+div);
let var1="18";
let var2="20";
let final = var1 + var2;
console.log(final);
final = var1- var2;
console.log(final);