let var1 = 5;
let var2 = 10;
console.log('Variables Before swapping ');
console.log("var1 = " + var1);
console.log("var2 = " + var2);
console.log('Variables After the Swapping :');
let temp = var1;
var1 = var2;
var2 = temp;
console.log("var1 = " + var1);
console.log("var2 = " + var2);